# Generated by Django 3.1.7 on 2021-04-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orange', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='episodes',
            field=models.CharField(default='', max_length=4),
        ),
    ]
