# Generated by Django 3.1.7 on 2021-04-04 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_title_episodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='release_date',
            field=models.CharField(default='', max_length=50),
        ),
    ]
